apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-cluster-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: github-runner-sa
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
