apiVersion: v1
kind: Service
metadata:
  name: airline-postgres
  namespace: default
  labels:
    app: airline-postgres
    service: airline-postgres
spec:
  type: ClusterIP
  selector:
    app: airline-postgres
  ports:
    - name: airline-postgres
      port: 5432
      targetPort: 5433
