apiVersion: v1
kind: Service
metadata:
  name: airport-location
  namespace: default
  labels:
    app: airport-location
    service: airport-location
spec:
  type: LoadBalancer
  selector:
    app: airport-location
  ports:
    - name: airport-location
      port: 8080
      targetPort: 8080
