apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: airport-core-github-runner
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: github-runner-sa
      automountServiceAccountToken: true
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      labels:
        - airport-core-k8s
      repository: cichan02/micro-airport-core
      workVolumeClaimTemplate:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      env: []
