apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-core-configmap
  namespace: default
data:
  POSTGRES_HOST: "core-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_SCHEMA: "public"
  POSTGRES_DB: "postgres"
