apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: default
  labels:
    app: mail-service
    service: mail-service
spec:
  type: LoadBalancer
  selector:
    app: mail-service
  ports:
    - name: mail-service
      port: 8080
      targetPort: 8082