apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
    service: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - name: auth-service
      port: 8080
      targetPort: 8083
